[package]
name = "eambar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = { version = "0.8", features = ["specs"] }
log = "0.4.17"
specs = { version = "0.18", features = ["derive"] }